/**
 * Auswendig API
 * RESTful API for Auswendig Flash Card Application.
 *
 * OpenAPI spec version: 1.0
 * Contact: hgmtrebing@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A schema to encapsulate card data.
 */
export interface CardSchema { 
    /**
     * The identifer for this Card.
     */
    cardExternalId?: string;
    /**
     * The identifier for the deck that owns this card.
     */
    deckExternalId?: string;
    /**
     * The question for this card.
     */
    question?: string;
    /**
     * The answer for this card.
     */
    answer?: string;
    /**
     * The note for this card.
     */
    note?: string;
    /**
     * The hint for this card.
     */
    hint?: string;
    /**
     * The success count for this code.
     */
    successCount?: number;
    /**
     * The failure count for this card.
     */
    failureCount?: number;
    /**
     * The last success date for this card.
     */
    lastSuccess?: Date;
    /**
     * The last failure date for this card.
     */
    lastFailure?: Date;
}