/**
 * Auswendig API
 * RESTful API for Auswendig Flash Card Application.
 *
 * OpenAPI spec version: 1.0
 * Contact: hgmtrebing@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Schema to encapsulate deck data (without cards).
 */
export interface CardlessDeckSchema { 
    /**
     * The System Identifier for this deck.
     */
    externalId?: string;
    /**
     * The name of the given deck.
     */
    deckName?: string;
    /**
     * The description of the given deck.
     */
    deckDescription?: string;
    /**
     * The username of the deck's owner.
     */
    ownerUsername?: string;
    /**
     * A global hint for all cards and sides.
     */
    globalHint?: string;
    /**
     * A global note for all cards and sides.
     */
    globalNote?: string;
    /**
     * The name for the question side.
     */
    questionSideName?: string;
    /**
     * The name for the answer side.
     */
    answerSideName?: string;
    /**
     * The total success count for this deck.
     */
    successCount?: number;
    /**
     * The total failure count for this deck.
     */
    failureCount?: number;
    /**
     * The last success date for this deck.
     */
    lastSuccess?: Date;
    /**
     * The last failure date for this deck.
     */
    lastFailure?: Date;
}