/**
 * Auswendig API
 * RESTful API for Auswendig Flash Card Application.
 *
 * OpenAPI spec version: 1.0
 * Contact: hgmtrebing@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Schema to encapsulate user data.
 */
export interface UserSchema { 
    /**
     * The user's unique username.
     */
    username?: string;
    /**
     * The user's first name.
     */
    firstName?: string;
    /**
     * The user's last name.
     */
    lastName?: string;
}