/**
 * Auswendig API
 * RESTful API for Auswendig Flash Card Application.
 *
 * OpenAPI spec version: 1.0
 * Contact: hgmtrebing@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CardlessDeckSchema } from '../model/cardlessDeckSchema';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DeckControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Add a Cardless Deck.
     * Add a new Cardless Deck to the System.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addCardlessDeck(body: CardlessDeckSchema, observe?: 'body', reportProgress?: boolean): Observable<CardlessDeckSchema>;
    public addCardlessDeck(body: CardlessDeckSchema, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CardlessDeckSchema>>;
    public addCardlessDeck(body: CardlessDeckSchema, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CardlessDeckSchema>>;
    public addCardlessDeck(body: CardlessDeckSchema, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling addCardlessDeck.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<CardlessDeckSchema>('post',`${this.basePath}/api/v1/deck/add-cardless-deck`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get All Cardless Decks.
     * Get All Cardless Decks in the System.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllDecksCardless(observe?: 'body', reportProgress?: boolean): Observable<Array<CardlessDeckSchema>>;
    public getAllDecksCardless(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CardlessDeckSchema>>>;
    public getAllDecksCardless(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CardlessDeckSchema>>>;
    public getAllDecksCardless(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<CardlessDeckSchema>>('get',`${this.basePath}/api/v1/deck/get-all-cardless-decks`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update Cardless Deck.
     * Updates a pre-existing Cardless Deck in the Systm.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateCardlessDeck(body: CardlessDeckSchema, observe?: 'body', reportProgress?: boolean): Observable<CardlessDeckSchema>;
    public updateCardlessDeck(body: CardlessDeckSchema, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CardlessDeckSchema>>;
    public updateCardlessDeck(body: CardlessDeckSchema, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CardlessDeckSchema>>;
    public updateCardlessDeck(body: CardlessDeckSchema, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateCardlessDeck.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<CardlessDeckSchema>('put',`${this.basePath}/api/v1/deck/update-cardless-deck`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
